import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const raw = fs.readFileSync(
  path.join(__dirname, "../src/data/anime.json"),
  "utf8"
);
const db = JSON.parse(raw);

const esc = (s) => String(s ?? "").replace(/'/g, "''");
const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);

const QUALITY = ["HD", "4K", "FHD", "SUB"];
const AGE = ["PG", "PG-13", "R", "NC-17", "G"];

const allAnime = [];
const seen = new Set();
for (const list of Object.values(db)) {
  for (const a of list) {
    if (!seen.has(a.id) && a.coverImage) {
      seen.add(a.id);
      allAnime.push(a);
    }
  }
}

const setOf = (list) => new Set(list.map((a) => a.id));
const trendingIds = setOf(db.trending);
const topSeriesIds = setOf(db.topToday);
const topMoviesIds = setOf(db.topMovies);

const heroSlides = db.trending.filter((a) => a.bannerImage).slice(0, 6);
const librarySlides = [...db.trending, ...db.popular, ...db.movies]
  .filter((a) => a.bannerImage)
  .slice(6, 12);
const heroIds = new Set(heroSlides.map((a) => a.id));

const genreMap = new Map();
let genreId = 1;
for (const a of allAnime) {
  for (const g of a.genres) {
    if (!genreMap.has(g)) {
      genreMap.set(g, { id: genreId++, slug: slugify(g), name: g });
    }
  }
}

const usedSlugs = new Set();
const slugFor = (a) => {
  let s = slugify(a.title) || `anime-${a.id}`;
  let base = s;
  let n = 1;
  while (usedSlugs.has(s)) s = `${base}-${n++}`;
  usedSlugs.add(s);
  return s;
};

const topics = [
  { name: "Action", color: "#104aa8", genre: "Action" },
  { name: "Romance", color: "#7fb237", genre: "Romance" },
  { name: "Isekai", color: "#b56129", genre: "Fantasy" },
  { name: "Slice of Life", color: "#d38d30", genre: "Slice of Life" },
  { name: "Mecha", color: "#b625ea", genre: "Mecha" },
  { name: "Horror", color: "#e023a7", genre: "Horror" },
  { name: "Sports", color: "#18ba2d", genre: "Sports" },
  { name: "Adventure", color: "#590020", genre: "Adventure" },
];

const sections = [
  { slug: "categories", title: "What are you interested in?", kind: "topics", panel: false, sort: 1, items: null },
  { slug: "new-series", title: "New Anime Series", kind: "panel", panel: true, sort: 2, items: db.trending },
  { slug: "new-anime-movies", title: "New Anime Movies", kind: "carousel", panel: false, sort: 3, items: db.movies },
  { slug: "airing", title: "Airing Now", kind: "carousel", panel: false, sort: 4, items: db.airing },
  { slug: "new-anime", title: "New Anime", kind: "carousel", panel: false, sort: 5, items: db.popular },
  { slug: "top-series", title: "Top 10 Anime Series Today", kind: "top10", panel: false, sort: 6, items: db.topToday },
  { slug: "action-anime", title: "Action Anime", kind: "carousel", panel: false, sort: 7, items: db.action },
  { slug: "top-movies", title: "Top 10 Anime Movies Today", kind: "top10", panel: false, sort: 8, items: db.topMovies },
  { slug: "library", title: "Latest Anime Library", kind: "slider", panel: false, sort: 9, items: librarySlides },
  { slug: "browse", title: "Browse", kind: "filter", panel: false, sort: 10, items: allAnime },
  { slug: "horror", title: "Horror Anime", kind: "carousel", panel: false, sort: 11, items: db.horror },
  { slug: "anime-movies", title: "Anime Movies", kind: "carousel", panel: false, sort: 12, items: db.movies },
  { slug: "slice-of-life", title: "Slice of Life Anime", kind: "carousel", panel: false, sort: 13, items: db.family },
];

const menu = [
  { label: "Home", href: "/#hero", sort: 1 },
  { label: "Anime", href: "/#browse", dropdown: true, sort: 2 },
  { label: "Movies", href: "/#anime-movies", sort: 3 },
  { label: "Series", href: "/#new-series", sort: 4 },
  { label: "Genres", href: "/#categories", dropdown: true, sort: 5 },
  { label: "Top Airing", href: "/#airing", badge: "New", sort: 6 },
  { label: "Request", href: "/#contact", sort: 7 },
];

const lines = [];
lines.push("-- AniLanka seed data (generated by scripts/generate-seed.mjs)");
lines.push("-- Run this AFTER the migration. Safe to re-run (truncates content tables).");
lines.push("");
lines.push("begin;");
lines.push("");
lines.push("truncate table");
lines.push(
  "  public.section_items, public.sections, public.hero_slides, public.topics,",
  "  public.episodes, public.anime_genres, public.anime, public.genres,",
  "  public.menu_items"
);
lines.push("restart identity cascade;");
lines.push("");

// genres
lines.push("-- GENRES");
for (const g of [...genreMap.values()].sort((a, b) => a.id - b.id)) {
  lines.push(
    `insert into public.genres (id, slug, name) values (${g.id}, '${esc(g.slug)}', '${esc(g.name)}');`
  );
}
lines.push("");

// anime
lines.push("-- ANIME");
for (const a of allAnime) {
  const quality = QUALITY[a.id % QUALITY.length];
  const isTopSeries = topSeriesIds.has(a.id);
  const isTopMovies = topMoviesIds.has(a.id);
  const topPosSeries = [...db.topToday].findIndex((x) => x.id === a.id) + 1;
  const topPosMovies = [...db.topMovies].findIndex((x) => x.id === a.id) + 1;
  lines.push(
    `insert into public.anime (` +
      `id, anilist_id, slug, title, romaji, description, banner_image, cover_image, ` +
      `format, status, season_year, episodes_count, duration, average_score, popularity, ` +
      `age_rating, quality, is_dub, is_new, is_trending, is_top, top_position` +
      `) values (` +
      `${a.id}, ${a.id}, '${esc(slugFor(a))}', '${esc(a.title)}', '${esc(a.romaji)}', '${esc(a.description)}', ` +
      `${a.bannerImage ? `'${esc(a.bannerImage)}'` : "null"}, ${a.coverImage ? `'${esc(a.coverImage)}'` : "null"}, ` +
      `'${a.format || "TV"}', '${a.status || "FINISHED"}', ${a.seasonYear || "null"}, ` +
      `${a.episodes || 0}, ${a.duration || "null"}, ${a.averageScore || "null"}, ${Math.round((a.averageScore || 0) * 1000)}, ` +
      `'${AGE[a.id % AGE.length]}', '${quality}', ${a.id % 3 !== 0}, ${trendingIds.has(a.id) || heroIds.has(a.id)}, ` +
      `${trendingIds.has(a.id)}, ${isTopSeries || isTopMovies}, ` +
      `${isTopSeries ? topPosSeries : isTopMovies ? topPosMovies : "null"}` +
      `);`
  );
}
lines.push("");

// anime_genres
lines.push("-- ANIME_GENRES");
for (const a of allAnime) {
  for (const g of a.genres || []) {
    const row = genreMap.get(g);
    if (row) {
      lines.push(
        `insert into public.anime_genres (anime_id, genre_id) values (${a.id}, ${row.id});`
      );
    }
  }
}
lines.push("");

// episodes (placeholders, capped at 40 per title)
lines.push("-- EPISODES");
let epCount = 0;
for (const a of allAnime) {
  if (a.format === "MOVIE" || a.format === "SPECIAL" || !a.episodes) continue;
  const total = Math.min(a.episodes, 40);
  for (let n = 1; n <= total; n++) {
    lines.push(
      `insert into public.episodes (anime_id, episode_number, title, duration) ` +
        `values (${a.id}, ${n}, null, ${a.duration || "null"});`
    );
    epCount++;
  }
}
lines.push("");

// topics
lines.push("-- TOPICS");
topics.forEach((t, i) => {
  const hit = allAnime.find((a) => a.genres.includes(t.genre));
  const img = hit?.coverImage ?? "";
  const g = genreMap.get(t.genre);
  lines.push(
    `insert into public.topics (name, slug, color, image_url, genre_id, sort_order) ` +
      `values ('${esc(t.name)}', '${esc(slugify(t.name))}', '${t.color}', ` +
      `${img ? `'${esc(img)}'` : "null"}, ${g ? g.id : "null"}, ${i + 1});`
  );
});
lines.push("");

// sections + section_items
lines.push("-- SECTIONS + SECTION_ITEMS");
for (const s of sections) {
  lines.push(
    `insert into public.sections (slug, title, kind, panel, view_all_url, sort_order) ` +
      `values ('${s.slug}', '${esc(s.title)}', '${s.kind}', ${s.panel}, '#', ${s.sort});`
  );
  if (s.items) {
    s.items.forEach((a, i) => {
      lines.push(
        `insert into public.section_items (section_id, anime_id, position) ` +
          `values ((select id from public.sections where slug = '${s.slug}'), ${a.id}, ${i + 1});`
      );
    });
  }
}
lines.push("");

// hero slides
lines.push("-- HERO SLIDES");
heroSlides.forEach((a, i) => {
  lines.push(
    `insert into public.hero_slides (anime_id, position) values (${a.id}, ${i + 1});`
  );
});
lines.push("");

// menu items
lines.push("-- MENU ITEMS");
for (const m of menu) {
  lines.push(
    `insert into public.menu_items (label, href, badge, has_dropdown, sort_order) ` +
      `values ('${esc(m.label)}', '${esc(m.href)}', ${m.badge ? `'${esc(m.badge)}'` : "null"}, ` +
      `${m.dropdown ? "true" : "false"}, ${m.sort});`
  );
}
lines.push("");

// settings
lines.push("-- SETTINGS");
lines.push(
  `insert into public.settings (key, value) values ` +
    `('site', '{"name":"AniLanka","tagline":"Watch anime online","copyright":"Copyright © 2026 AniLanka. All rights reserved."}'::jsonb), ` +
    `('footer', '{"genres":["Action","Adventure","Romance","Horror","Drama","Fantasy","Comedy","Thriller","Slice of Life","Sci-Fi","Mecha","Sports"],"help":["My Account","Customer Support","Contact Us","Advertise","Jobs"],"company":["View Plans","Blog","Devices","About Us"]}'::jsonb), ` +
    `('socials', '[{"label":"Facebook","href":"#"},{"label":"X","href":"#"},{"label":"GitHub","href":"#"},{"label":"YouTube","href":"#"}]'::jsonb) ` +
    `on conflict (key) do update set value = excluded.value;`
);
lines.push("");
lines.push("commit;");
lines.push("");
lines.push(`-- Seeded: ${allAnime.length} anime, ${genreMap.size} genres, ${epCount} episodes, ${topics.length} topics, ${sections.length} sections`);

const out = path.join(__dirname, "../supabase/seed.sql");
fs.writeFileSync(out, lines.join("\n"));
console.log(`Wrote supabase/seed.sql (${lines.length} statements)`);
