-- ============================================================
-- ANIMELK - Supabase schema
-- Manages everything on the website: content, homepage layout,
-- navigation, site settings, users, watchlist, history, ratings.
-- Images are NOT stored in Supabase storage - they are external
-- URLs (CDN) stored as text columns.
-- ============================================================

-- ---------- GENRES ----------
create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

-- ---------- ANIME ----------
create table if not exists public.anime (
  id bigint generated by default as identity primary key,
  anilist_id bigint unique,
  slug text not null unique,
  title text not null,
  romaji text,
  description text,
  banner_image text,
  cover_image text,
  format text not null default 'TV'
    check (format in ('TV','MOVIE','OVA','ONA','SPECIAL','TV_SHORT','MUSIC','OTHER')),
  status text not null default 'FINISHED'
    check (status in ('RELEASING','FINISHED','NOT_YET_RELEASED','CANCELLED','HIATUS')),
  season_year integer,
  season text check (season in ('WINTER','SPRING','SUMMER','FALL')),
  episodes_count integer not null default 0,
  duration integer,
  average_score numeric(4,1),
  popularity bigint not null default 0,
  age_rating text not null default 'PG-13'
    check (age_rating in ('G','PG','PG-13','R','NC-17')),
  quality text not null default 'HD' check (quality in ('HD','FHD','4K','SUB')),
  is_dub boolean not null default false,
  is_new boolean not null default false,
  is_trending boolean not null default false,
  is_top boolean not null default false,
  top_position integer,
  trailer_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists anime_slug_idx on public.anime (slug);
create index if not exists anime_trending_idx on public.anime (is_trending desc, popularity desc);
create index if not exists anime_top_idx on public.anime (is_top desc, top_position);
create index if not exists anime_score_idx on public.anime (average_score desc nulls last);

-- ---------- ANIME <-> GENRES ----------
create table if not exists public.anime_genres (
  anime_id bigint not null references public.anime(id) on delete cascade,
  genre_id bigint not null references public.genres(id) on delete cascade,
  primary key (anime_id, genre_id)
);

-- ---------- EPISODES ----------
create table if not exists public.episodes (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  episode_number integer not null,
  title text,
  video_url text,
  thumbnail text,
  duration integer,
  is_premium boolean not null default false,
  subtitles jsonb not null default '[]'::jsonb,
  unique (anime_id, episode_number)
);

create index if not exists episodes_anime_idx on public.episodes (anime_id, episode_number);

-- ---------- TOPICS (homepage category tiles) ----------
create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  color text not null default '#7b61ff',
  image_url text,
  genre_id bigint references public.genres(id) on delete set null,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

-- ---------- SECTIONS (homepage rows) ----------
create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  kind text not null default 'carousel'
    check (kind in ('carousel','top10','grid','slider','panel','filter','topics')),
  panel boolean not null default false,
  view_all_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

-- ---------- SECTION ITEMS (which anime, in which order) ----------
create table if not exists public.section_items (
  section_id bigint not null references public.sections(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  position integer not null default 0,
  primary key (section_id, anime_id)
);

-- ---------- HERO SLIDES ----------
create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  position integer not null default 0,
  is_active boolean not null default true
);

-- ---------- MENU ITEMS (navbar) ----------
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null,
  badge text,
  has_dropdown boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

-- ---------- SETTINGS (site-wide key/value) ----------
create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- ---------- PROFILES (extends auth.users) ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text,
  role text not null default 'member' check (role in ('member','admin')),
  created_at timestamptz not null default now()
);

-- ---------- WATCHLIST ----------
create table if not exists public.watchlist (
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, anime_id)
);

-- ---------- WATCH HISTORY ----------
create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  episode_id bigint references public.episodes(id) on delete set null,
  position_seconds integer not null default 0,
  watched_at timestamptz not null default now()
);

create index if not exists watch_history_user_idx
  on public.watch_history (user_id, watched_at desc);

-- ---------- RATINGS & REVIEWS ----------
create table if not exists public.ratings (
  user_id uuid not null references auth.users(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  rating smallint not null check (rating between 1 and 10),
  review text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, anime_id)
);

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

create or replace function public.set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists anime_updated_at on public.anime;
create trigger anime_updated_at before update on public.anime
  for each row execute function public.set_updated_at();

drop trigger if exists ratings_updated_at on public.ratings;
create trigger ratings_updated_at before update on public.ratings
  for each row execute function public.set_updated_at();

drop trigger if exists settings_updated_at on public.settings;
create trigger settings_updated_at before update on public.settings
  for each row execute function public.set_updated_at();

-- auto-create profile on signup
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- admin check helper
create or replace function public.is_admin() returns boolean as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$ language sql stable security definer;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.genres        enable row level security;
alter table public.anime         enable row level security;
alter table public.anime_genres  enable row level security;
alter table public.episodes      enable row level security;
alter table public.topics        enable row level security;
alter table public.sections      enable row level security;
alter table public.section_items enable row level security;
alter table public.hero_slides   enable row level security;
alter table public.menu_items    enable row level security;
alter table public.settings      enable row level security;
alter table public.profiles      enable row level security;
alter table public.watchlist     enable row level security;
alter table public.watch_history enable row level security;
alter table public.ratings       enable row level security;

-- everyone can read content
create policy "public read genres"        on public.genres        for select using (true);
create policy "public read anime"         on public.anime         for select using (true);
create policy "public read anime_genres"  on public.anime_genres  for select using (true);
create policy "public read episodes"      on public.episodes      for select using (true);
create policy "public read topics"        on public.topics        for select using (true);
create policy "public read sections"      on public.sections      for select using (true);
create policy "public read section_items" on public.section_items for select using (true);
create policy "public read hero_slides"   on public.hero_slides   for select using (true);
create policy "public read menu_items"    on public.menu_items    for select using (true);
create policy "public read settings"      on public.settings      for select using (true);
create policy "public read profiles"      on public.profiles      for select using (true);

-- users manage only their own rows
create policy "own watchlist" on public.watchlist
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own watch_history" on public.watch_history
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own ratings" on public.ratings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own profile select-update" on public.profiles
  for select using (auth.uid() = id);
create policy "own profile update" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "own profile insert" on public.profiles
  for insert with check (auth.uid() = id);

-- admins manage all content
create policy "admin manage genres"        on public.genres
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage anime"         on public.anime
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage anime_genres"  on public.anime_genres
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage episodes"      on public.episodes
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage topics"        on public.topics
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage sections"      on public.sections
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage section_items" on public.section_items
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage hero_slides"   on public.hero_slides
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage menu_items"    on public.menu_items
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage settings"      on public.settings
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage profiles"      on public.profiles
  for all using (public.is_admin()) with check (public.is_admin());
