-- ============================================================
-- ANIMELK - Anime Request system
--
-- Public "Request an Anime" page + admin request management.
--
--  * anime_requests          one row per unique anime/season/type
--                            (deduplicated on the external anime API id,
--                            never on the title, so spelling differences and
--                            English/Japanese/alternative titles can't create
--                            duplicates)
--  * anime_request_supports  one row per supporter ("vote"), used for the
--                            request_count and for analytics
--  * RPCs                    submit/support run server-side and bump the
--                            count atomically, so the browser can never send
--                            a request_count of its own
--
-- Run in the Supabase SQL editor (safe to re-run).
-- ============================================================

-- ---------- 1. Requests ----------
create table if not exists public.anime_requests (
  id bigint generated by default as identity primary key,
  -- external anime metadata provider + its stable id (AniList media id)
  source text not null default 'anilist',
  external_id bigint not null,
  -- snapshot of the anime metadata at request time
  anime_title text not null,
  anime_title_english text,
  anime_title_native text,
  anime_romaji text,
  anime_cover text,
  anime_format text,
  anime_status text,
  anime_episodes integer,
  anime_year integer,
  -- which season is being requested (0 = the series as a whole)
  season integer not null default 0,
  season_year integer,
  season_label text,
  request_type text not null default 'NEW_ANIME',
  request_count integer not null default 0,
  status text not null default 'REQUESTED',
  -- set by an admin when the title goes live, so the public page can offer
  -- a "Watch Now" link back into the existing catalogue
  added_anime_id bigint references public.anime(id) on delete set null,
  first_requested_at timestamptz not null default now(),
  last_requested_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint anime_requests_unique unique (source, external_id, request_type, season),
  constraint anime_requests_type_check
    check (request_type in ('NEW_ANIME','NEW_SEASON','MISSING_EPISODE','DUB','SUBTITLE','OTHER')),
  constraint anime_requests_status_check
    check (status in ('REQUESTED','UNDER_REVIEW','PLANNED','PROCESSING','ADDED','REJECTED'))
);

create index if not exists anime_requests_rank_idx
  on public.anime_requests (request_count desc, last_requested_at desc);
create index if not exists anime_requests_status_idx
  on public.anime_requests (status, request_count desc);
create index if not exists anime_requests_recent_idx
  on public.anime_requests (last_requested_at desc);
create index if not exists anime_requests_first_idx
  on public.anime_requests (first_requested_at desc);
create index if not exists anime_requests_external_idx
  on public.anime_requests (source, external_id);

drop trigger if exists anime_requests_updated_at on public.anime_requests;
create trigger anime_requests_updated_at before update on public.anime_requests
  for each row execute function public.set_updated_at();

-- ---------- 2. Supports (votes) ----------
create table if not exists public.anime_request_supports (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.anime_requests(id) on delete cascade,
  -- authenticated user id, or a random device-scoped id for anonymous
  -- visitors. No personal information is stored.
  supporter_key text not null,
  message text,
  created_at timestamptz not null default now(),
  unique (request_id, supporter_key)
);

create index if not exists anime_request_supports_request_idx
  on public.anime_request_supports (request_id);
create index if not exists anime_request_supports_created_idx
  on public.anime_request_supports (created_at desc);
create index if not exists anime_request_supports_key_idx
  on public.anime_request_supports (supporter_key);

-- ---------- 3. Row Level Security ----------
alter table public.anime_requests         enable row level security;
alter table public.anime_request_supports enable row level security;

-- The request list is public content (counts, status, metadata).
drop policy if exists "public read anime_requests" on public.anime_requests;
create policy "public read anime_requests" on public.anime_requests
  for select using (true);

-- Supports are NOT public: they carry the optional user message and the
-- supporter key. Admins read them; everyone else goes through the RPCs.
drop policy if exists "admin manage anime_requests" on public.anime_requests;
create policy "admin manage anime_requests" on public.anime_requests
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin manage anime_request_supports" on public.anime_request_supports;
create policy "admin manage anime_request_supports" on public.anime_request_supports
  for all using (public.is_admin()) with check (public.is_admin());

-- ---------- 4. RPCs ----------
-- Counts are only ever written here, never by the browser.

create or replace function public.anime_request_key_ok(p_key text)
returns boolean as $$
  select length(trim(coalesce(p_key, ''))) between 8 and 128;
$$ language sql immutable;

-- Create a request, or support it when it already exists.
create or replace function public.submit_anime_request(
  p_source text,
  p_external_id bigint,
  p_title text,
  p_title_english text,
  p_title_native text,
  p_romaji text,
  p_cover text,
  p_format text,
  p_status text,
  p_episodes integer,
  p_year integer,
  p_season integer,
  p_season_label text,
  p_season_year integer,
  p_request_type text,
  p_supporter_key text,
  p_message text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text := trim(coalesce(p_supporter_key, ''));
  v_type text := upper(coalesce(nullif(trim(p_request_type), ''), 'NEW_ANIME'));
  v_source text := lower(coalesce(nullif(trim(p_source), ''), 'anilist'));
  v_season integer := greatest(coalesce(p_season, 0), 0);
  v_row public.anime_requests;
  v_added boolean := false;
  v_total integer := 0;
  v_recent integer := 0;
begin
  if not public.anime_request_key_ok(v_key) then
    raise exception 'invalid supporter key';
  end if;
  if p_external_id is null or p_external_id <= 0 then
    raise exception 'invalid anime id';
  end if;
  if p_title is null or length(trim(p_title)) = 0 then
    raise exception 'missing title';
  end if;
  if v_type not in ('NEW_ANIME','NEW_SEASON','MISSING_EPISODE','DUB','SUBTITLE','OTHER') then
    raise exception 'invalid request type';
  end if;

  -- Light spam guard: one device/session may contribute at most 40 times a day.
  select count(*) into v_recent
    from public.anime_request_supports
   where supporter_key = v_key and created_at > now() - interval '1 day';
  if v_recent >= 40 then
    raise exception 'rate limited';
  end if;

  insert into public.anime_requests as r (
    source, external_id, anime_title, anime_title_english, anime_title_native, anime_romaji,
    anime_cover, anime_format, anime_status, anime_episodes, anime_year,
    season, season_label, season_year, request_type
  ) values (
    v_source, p_external_id, trim(p_title),
    nullif(trim(coalesce(p_title_english, '')), ''),
    nullif(trim(coalesce(p_title_native, '')), ''),
    nullif(trim(coalesce(p_romaji, '')), ''),
    nullif(trim(coalesce(p_cover, '')), ''),
    nullif(trim(coalesce(p_format, '')), ''),
    nullif(trim(coalesce(p_status, '')), ''),
    p_episodes, p_year,
    v_season, nullif(trim(coalesce(p_season_label, '')), ''), p_season_year, v_type
  )
  on conflict (source, external_id, request_type, season) do update
    set last_requested_at = now(),
        anime_cover = coalesce(r.anime_cover, excluded.anime_cover),
        anime_title_english = coalesce(r.anime_title_english, excluded.anime_title_english),
        anime_title_native = coalesce(r.anime_title_native, excluded.anime_title_native),
        anime_format = coalesce(r.anime_format, excluded.anime_format),
        anime_year = coalesce(r.anime_year, excluded.anime_year),
        anime_episodes = coalesce(r.anime_episodes, excluded.anime_episodes)
  returning * into v_row;

  insert into public.anime_request_supports (request_id, supporter_key, message)
  values (v_row.id, v_key, nullif(left(trim(coalesce(p_message, '')), 300), ''))
  on conflict (request_id, supporter_key) do nothing
  returning true into v_added;
  v_added := coalesce(v_added, false);

  if v_added then
    update public.anime_requests
       set request_count = request_count + 1
     where id = v_row.id
    returning * into v_row;
  end if;

  select count(*) into v_total
    from public.anime_request_supports where request_id = v_row.id;

  return jsonb_build_object(
    'request', to_jsonb(v_row),
    'already_supported', not v_added,
    'created', v_total = 1
  );
end;
$$;

-- Support an existing request (no duplicate row, count goes up by one).
create or replace function public.support_anime_request(
  p_request_id bigint,
  p_supporter_key text,
  p_message text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text := trim(coalesce(p_supporter_key, ''));
  v_row public.anime_requests;
  v_added boolean := false;
  v_recent integer := 0;
begin
  if not public.anime_request_key_ok(v_key) then
    raise exception 'invalid supporter key';
  end if;
  if p_request_id is null or p_request_id <= 0 then
    raise exception 'invalid request id';
  end if;

  select count(*) into v_recent
    from public.anime_request_supports
   where supporter_key = v_key and created_at > now() - interval '1 day';
  if v_recent >= 40 then
    raise exception 'rate limited';
  end if;

  insert into public.anime_request_supports (request_id, supporter_key, message)
  values (p_request_id, v_key, nullif(left(trim(coalesce(p_message, '')), 300), ''))
  on conflict (request_id, supporter_key) do nothing
  returning true into v_added;
  v_added := coalesce(v_added, false);

  if v_added then
    update public.anime_requests
       set request_count = request_count + 1,
           last_requested_at = now()
     where id = p_request_id
    returning * into v_row;
  else
    select * into v_row from public.anime_requests where id = p_request_id;
  end if;

  if v_row.id is null then
    raise exception 'request not found';
  end if;

  return jsonb_build_object(
    'request', to_jsonb(v_row),
    'already_supported', not v_added,
    'created', false
  );
end;
$$;

-- Request ids this visitor has already supported (drives "✓ You supported this").
create or replace function public.anime_request_support_ids(p_supporter_key text)
returns setof bigint
language sql
security definer
set search_path = public
as $$
  select request_id
    from public.anime_request_supports
   where supporter_key = trim(coalesce(p_supporter_key, ''))
     and public.anime_request_key_ok(p_supporter_key);
$$;

grant execute on function public.anime_request_key_ok(text)            to anon, authenticated;
grant execute on function public.anime_request_support_ids(text)       to anon, authenticated;
grant execute on function public.submit_anime_request(
  text, bigint, text, text, text, text, text, text, text,
  integer, integer, integer, text, integer, text, text, text
) to anon, authenticated;
grant execute on function public.support_anime_request(bigint, text, text)
  to anon, authenticated;

-- ---------- 5. Realtime ----------
-- Lets the public request counts update without a refresh.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'anime_requests'
    ) then
      alter publication supabase_realtime add table public.anime_requests;
    end if;
  end if;
exception when others then
  raise notice 'Realtime publication not updated: %', sqlerrm;
end $$;
