-- ============================================================
-- ANIMELK - Multiple abyss.to accounts for subtitle uploads
--
-- Subtitle uploads used to log in with a single account held in
-- Edge Function secrets (ABYSS_EMAIL / ABYSS_PASSWORD). This adds
-- a pool of accounts in the database: the abyss-sub function picks
-- the least-recently-used active account and automatically falls
-- back to the next one when a login or upload fails. The old
-- secrets keep working as a final fallback, so nothing breaks
-- while no accounts have been added yet.
--
-- SECURITY
--   Passwords must be stored recoverable, because the function has
--   to replay them to POST api.abyss.to/auth/login - they cannot be
--   hashed. So this table is closed to every client:
--     * RLS is enabled with NO policies (denies everything)
--     * anon and authenticated have all grants revoked
--   Only the service role - used exclusively inside the abyss-sub
--   Edge Function - can read the rows. Admins manage accounts
--   through the SECURITY DEFINER functions below, which are the
--   only path that touches the table and never return a password.
--
-- Run in the Supabase SQL editor (safe to re-run).
-- ============================================================

create table if not exists public.abyss_accounts (
  id bigint generated by default as identity primary key,
  label text not null default '',
  username text not null,
  password text not null,
  is_active boolean not null default true,
  last_used_at timestamptz,
  last_ok_at timestamptz,
  last_error text,
  failure_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One row per account; same login address cannot be added twice.
create unique index if not exists abyss_accounts_username_idx
  on public.abyss_accounts (lower(username));

-- ---------- 1. Close the table to every client ----------
alter table public.abyss_accounts enable row level security;

-- Belt and braces: RLS alone would deny (no policies), but remove the
-- default grants as well so nothing can even attempt a read.
revoke all on table public.abyss_accounts from anon, authenticated;
grant all on table public.abyss_accounts to service_role;

-- Adds an account (p_id null) or updates one; a blank p_password on an
-- update keeps the stored password, so renaming never needs a re-type.
create or replace function public.abyss_account_save(
  p_id bigint,
  p_label text,
  p_username text,
  p_password text
) returns bigint as $$
declare
  v_id bigint;
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  if coalesce(trim(p_username), '') = '' then
    raise exception 'An abyss username or email is required.' using errcode = '22023';
  end if;

  if p_id is null then
    if coalesce(trim(p_password), '') = '' then
      raise exception 'A password is required for a new account.' using errcode = '22023';
    end if;
    insert into public.abyss_accounts (label, username, password)
    values (coalesce(trim(p_label), ''), trim(p_username), p_password)
    returning id into v_id;
  else
    update public.abyss_accounts
       set label = coalesce(trim(p_label), ''),
           username = trim(p_username),
           password = case
                        when coalesce(trim(p_password), '') = '' then password
                        else p_password
                      end,
           updated_at = now()
     where id = p_id
     returning id into v_id;

    if v_id is null then
      raise exception 'That account no longer exists.' using errcode = 'P0002';
    end if;
  end if;

  return v_id;
end $$ language plpgsql security definer set search_path = public;

-- Metadata only. The password is deliberately never returned, so it
-- cannot leak into the browser console, network tab or a React state tree.
create or replace function public.abyss_accounts_list()
returns table (
  id bigint,
  label text,
  username text,
  is_active boolean,
  last_used_at timestamptz,
  last_ok_at timestamptz,
  last_error text,
  failure_count integer,
  created_at timestamptz
) as $$
  select a.id,
         a.label,
         a.username,
         a.is_active,
         a.last_used_at,
         a.last_ok_at,
         a.last_error,
         a.failure_count,
         a.created_at
    from public.abyss_accounts a
   where public.is_admin()
   order by a.id;
$$ language sql stable security definer set search_path = public;

create or replace function public.abyss_account_set_active(p_id bigint, p_active boolean)
returns void as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  update public.abyss_accounts
     set is_active = p_active, updated_at = now()
   where id = p_id;
end $$ language plpgsql security definer set search_path = public;

create or replace function public.abyss_account_delete(p_id bigint)
returns void as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  delete from public.abyss_accounts where id = p_id;
end $$ language plpgsql security definer set search_path = public;

-- ---------- 2. Result tracking, for the abyss-sub function only ----------
-- Called with the service role after each attempt. Recording last_used_at
-- on every attempt is what spreads uploads across the accounts; the failure
-- counters exist so the admin panel can show which account has gone stale.
create or replace function public.abyss_account_mark(
  p_id bigint,
  p_ok boolean,
  p_error text default null
) returns void as $$
begin
  update public.abyss_accounts
     set last_used_at = now(),
         last_ok_at = case when p_ok then now() else last_ok_at end,
         last_error = case when p_ok then null else left(coalesce(p_error, ''), 500) end,
         failure_count = case when p_ok then 0 else failure_count + 1 end,
         updated_at = now()
   where id = p_id;
end $$ language plpgsql security definer set search_path = public;

-- ---------- 3. Grants ----------
-- Functions are executable by PUBLIC by default, so revoke that first.
revoke all on function public.abyss_account_save(bigint, text, text, text) from public;
revoke all on function public.abyss_accounts_list() from public;
revoke all on function public.abyss_account_set_active(bigint, boolean) from public;
revoke all on function public.abyss_account_delete(bigint) from public;
revoke all on function public.abyss_account_mark(bigint, boolean, text) from public;

-- Admins (any authenticated caller - each function re-checks is_admin()).
grant execute on function public.abyss_account_save(bigint, text, text, text) to authenticated;
grant execute on function public.abyss_accounts_list() to authenticated;
grant execute on function public.abyss_account_set_active(bigint, boolean) to authenticated;
grant execute on function public.abyss_account_delete(bigint) to authenticated;

-- Only the Edge Function's service role may record attempt results.
grant execute on function public.abyss_account_mark(bigint, boolean, text) to service_role;

-- ---------- 4. Make sure the service role can reach the table ----------
grant usage, select on sequence public.abyss_accounts_id_seq to service_role;
