-- ============================================================
-- ANIMELK - Episode and movie comments
--
-- Every episode gets its own thread, and a movie that has no
-- episode row (a single video) hangs its thread off the title
-- itself, so episode_id stays null there.
--
-- SECURITY
--   Anyone may read a thread, but only a signed-in viewer may
--   write, and only rows carrying their own auth.uid() - the
--   client sends its user id, and the policy refuses anything
--   that does not match the session. Deleting is limited to the
--   author, so one viewer can never remove another's comment.
--
--   The display name and avatar are snapshotted on the row when
--   the comment is posted. Profiles carry a generated
--   "user_xxxxxxxx" name for Google sign-ins (usernames are
--   unique, real names are not), so a snapshot is what keeps the
--   thread readable; the cost is that a later name or avatar
--   change does not rewrite existing comments.
-- ============================================================

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  anime_id bigint not null references public.anime(id) on delete cascade,
  episode_id bigint references public.episodes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar text,
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);

-- Threads are read newest first, and the animelookup keeps the
-- per-title listing (a future "all comments on this anime" view)
-- from scanning the table.
create index if not exists comments_episode_idx on public.comments (episode_id, created_at desc);
create index if not exists comments_anime_idx on public.comments (anime_id, created_at desc);

alter table public.comments enable row level security;

-- the whole thread is public, signed in or not
create policy "public read comments" on public.comments
  for select using (true);

-- signed-in viewers post as themselves, nothing else
create policy "signed in viewers post comments" on public.comments
  for insert to authenticated with check (auth.uid() = user_id);

-- and may take back only what they wrote
create policy "viewers delete own comments" on public.comments
  for delete to authenticated using (auth.uid() = user_id);
